/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UseHookRouteImport } from './routes/use-hook'
import { Route as ReactCompilerRouteImport } from './routes/react-compiler'
import { Route as DeathOfForwardRefRouteImport } from './routes/death-of-forward-ref'
import { Route as ContextAsProviderRouteImport } from './routes/context-as-provider'
import { Route as IndexRouteImport } from './routes/index'

const UseHookRoute = UseHookRouteImport.update({
  id: '/use-hook',
  path: '/use-hook',
  getParentRoute: () => rootRouteImport,
} as any)
const ReactCompilerRoute = ReactCompilerRouteImport.update({
  id: '/react-compiler',
  path: '/react-compiler',
  getParentRoute: () => rootRouteImport,
} as any)
const DeathOfForwardRefRoute = DeathOfForwardRefRouteImport.update({
  id: '/death-of-forward-ref',
  path: '/death-of-forward-ref',
  getParentRoute: () => rootRouteImport,
} as any)
const ContextAsProviderRoute = ContextAsProviderRouteImport.update({
  id: '/context-as-provider',
  path: '/context-as-provider',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/context-as-provider': typeof ContextAsProviderRoute
  '/death-of-forward-ref': typeof DeathOfForwardRefRoute
  '/react-compiler': typeof ReactCompilerRoute
  '/use-hook': typeof UseHookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/context-as-provider': typeof ContextAsProviderRoute
  '/death-of-forward-ref': typeof DeathOfForwardRefRoute
  '/react-compiler': typeof ReactCompilerRoute
  '/use-hook': typeof UseHookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/context-as-provider': typeof ContextAsProviderRoute
  '/death-of-forward-ref': typeof DeathOfForwardRefRoute
  '/react-compiler': typeof ReactCompilerRoute
  '/use-hook': typeof UseHookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/context-as-provider'
    | '/death-of-forward-ref'
    | '/react-compiler'
    | '/use-hook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/context-as-provider'
    | '/death-of-forward-ref'
    | '/react-compiler'
    | '/use-hook'
  id:
    | '__root__'
    | '/'
    | '/context-as-provider'
    | '/death-of-forward-ref'
    | '/react-compiler'
    | '/use-hook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContextAsProviderRoute: typeof ContextAsProviderRoute
  DeathOfForwardRefRoute: typeof DeathOfForwardRefRoute
  ReactCompilerRoute: typeof ReactCompilerRoute
  UseHookRoute: typeof UseHookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/use-hook': {
      id: '/use-hook'
      path: '/use-hook'
      fullPath: '/use-hook'
      preLoaderRoute: typeof UseHookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/react-compiler': {
      id: '/react-compiler'
      path: '/react-compiler'
      fullPath: '/react-compiler'
      preLoaderRoute: typeof ReactCompilerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/death-of-forward-ref': {
      id: '/death-of-forward-ref'
      path: '/death-of-forward-ref'
      fullPath: '/death-of-forward-ref'
      preLoaderRoute: typeof DeathOfForwardRefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/context-as-provider': {
      id: '/context-as-provider'
      path: '/context-as-provider'
      fullPath: '/context-as-provider'
      preLoaderRoute: typeof ContextAsProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContextAsProviderRoute: ContextAsProviderRoute,
  DeathOfForwardRefRoute: DeathOfForwardRefRoute,
  ReactCompilerRoute: ReactCompilerRoute,
  UseHookRoute: UseHookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
